// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdgIqD496OT-ASJ-UHLUydxA3UagqyEmg',
    appId: '1:709442613771:web:32b705caba117be642cd0e',
    messagingSenderId: '709442613771',
    projectId: 'deal-dash-cf6e3',
    authDomain: 'deal-dash-cf6e3.firebaseapp.com',
    storageBucket: 'deal-dash-cf6e3.appspot.com',
    measurementId: 'G-GQTYWWY71K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzDONBIsXM0R_GNyUPqB-k5iDH4g3U74I',
    appId: '1:709442613771:android:f4f9db51d84a3fc442cd0e',
    messagingSenderId: '709442613771',
    projectId: 'deal-dash-cf6e3',
    storageBucket: 'deal-dash-cf6e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx-GKk08QXTsi3NEJZsXsXqEw0dXyhpCg',
    appId: '1:709442613771:ios:4254dd315a52ef1b42cd0e',
    messagingSenderId: '709442613771',
    projectId: 'deal-dash-cf6e3',
    storageBucket: 'deal-dash-cf6e3.appspot.com',
    iosBundleId: 'com.example.dealdash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx-GKk08QXTsi3NEJZsXsXqEw0dXyhpCg',
    appId: '1:709442613771:ios:4254dd315a52ef1b42cd0e',
    messagingSenderId: '709442613771',
    projectId: 'deal-dash-cf6e3',
    storageBucket: 'deal-dash-cf6e3.appspot.com',
    iosBundleId: 'com.example.dealdash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdgIqD496OT-ASJ-UHLUydxA3UagqyEmg',
    appId: '1:709442613771:web:7797c7f1df579c6342cd0e',
    messagingSenderId: '709442613771',
    projectId: 'deal-dash-cf6e3',
    authDomain: 'deal-dash-cf6e3.firebaseapp.com',
    storageBucket: 'deal-dash-cf6e3.appspot.com',
    measurementId: 'G-L4QMZMTGCH',
  );

}